name: Docker Image CI

on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths:
            - "simulation-service/**"
    pull_request:
        branches: ["main"]
        paths:
            - "simulation-service/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Get the date
              id: date
              run: echo "::set-output name=date::$(date +'%Y%m%d')"
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./simulation-service
                  file: ./simulation-service/Dockerfile
                  push: true
                  tags: jtoniolo/aquarium-time:${{ steps.date.outputs.date }}
