name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "simulation-service/**"
      - "aquarium-ui/**"
  pull_request:
    branches: ["main"]
    paths:
      - "simulation-service/**"
      - "aquarium-ui/**"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push simulation service
        uses: docker/build-push-action@v5
        with:
          context: ./simulation-service
          push: true
          tags: |
            ghcr.io/jtoniolo/aquarium-time-simulation:${{ steps.date.outputs.date }}-${{ github.run_number }}
            ghcr.io/jtoniolo/aquarium-time-simulation:latest

      - name: Build and push UI
        uses: docker/build-push-action@v5
        with:
          context: ./aquarium-ui
          push: true
          tags: |
            ghcr.io/jtoniolo/aquarium-time-ui:${{ steps.date.outputs.date }}-${{ github.run_number }}
            ghcr.io/jtoniolo/aquarium-time-ui:latest
